#!/usr/bin/env node
/**
 * Meme Evolution Analyzer — Step 1
 *
 * Sends top 5 and bottom 5 memes (with images) to Gemini Vision
 * for structured analysis of what works and what doesn't.
 *
 * Usage: node scripts/analyze-memes.mjs
 */

import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.backup' });

import { GoogleGenerativeAI } from '@google/generative-ai';

const data = JSON.parse(fs.readFileSync('/tmp/meme-analysis-data.json', 'utf8'));
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function fetchImageAsBase64(url) {
  try {
    const r = await fetch(url, { signal: AbortSignal.timeout(10000) });
    if (!r.ok) return null;
    const buf = Buffer.from(await r.arrayBuffer());
    const mime = r.headers.get('content-type') || 'image/jpeg';
    return { data: buf.toString('base64'), mimeType: mime };
  } catch { return null; }
}

console.log('Fetching images for top 5 and bottom 5...');

const parts = [];

parts.push({ text: `You are a meme quality analyst reviewing AI-generated crypto memes.

CONTEXT:
- These memes are generated by an AI engine (Gemini 3 Pro image model)
- Average quality score across ${data.total} memes: ${data.avg}/100
- Scores are assigned by a separate AI vision model (Gemini Flash)
- The engine uses "comedy strategies" (irony, cope, self_roast, etc.) and "art styles" (cyberpunk, pixel, oil painting, etc.)

I will show you TOP 5 (highest scoring) and BOTTOM 5 (lowest scoring) memes with their actual images.

After viewing all 10 memes, provide:

1. **VISUAL PATTERNS** — What visual elements make top memes succeed? What visual problems appear in bottom memes? (composition, clarity, character rendering, color palette)

2. **TEXT RENDERING** — How well is text/caption rendered in the images? Common issues? (garbled text, too small, wrong placement, unreadable)

3. **COMEDY + VISUAL ALIGNMENT** — Do the visuals actually convey the intended comedy strategy? Where does the visual miss the joke?

4. **ART STYLE ANALYSIS** — Which art styles produce the clearest, most impactful memes? Which ones cause visual noise?

5. **TOP 5 PROMPT IMPROVEMENTS** — Concrete, specific changes to the image generation prompt that would raise average quality. Write them as rules the prompt should include.

6. **TOP 3 ANTI-PATTERNS** — Things the image generation prompt should explicitly forbid to avoid recurring quality issues.

Be brutally honest and specific. Reference actual memes by title.` });

// Top 5
parts.push({ text: '\n\n=== TOP 5 MEMES (highest quality scores) ===' });
for (const m of data.top10.slice(0, 5)) {
  const img = await fetchImageAsBase64(m.imageUrl);
  if (img) {
    parts.push({ text: `\nTitle: "${m.title}" | Score: ${m.score}/100 | Strategy: ${m.strategy} | Style: ${m.artStyle}\nCaption: "${m.caption}"` });
    parts.push({ inlineData: img });
    console.log(`  Loaded: ${m.title} (${m.score})`);
  } else {
    console.log(`  FAILED: ${m.title} — ${m.imageUrl}`);
  }
}

// Bottom 5
parts.push({ text: '\n\n=== BOTTOM 5 MEMES (lowest quality scores) ===' });
for (const m of data.bottom10.slice(-5)) {
  const img = await fetchImageAsBase64(m.imageUrl);
  if (img) {
    parts.push({ text: `\nTitle: "${m.title}" | Score: ${m.score}/100 | Strategy: ${m.strategy} | Style: ${m.artStyle}\nCaption: "${m.caption}"` });
    parts.push({ inlineData: img });
    console.log(`  Loaded: ${m.title} (${m.score})`);
  } else {
    console.log(`  FAILED: ${m.title} — ${m.imageUrl}`);
  }
}

console.log(`\nSending ${parts.length} parts to Gemini 2.5 Flash for vision analysis...\n`);

const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
const result = await model.generateContent(parts);
const text = result.response.text();

console.log(text);

fs.writeFileSync('/tmp/meme-evolution-analysis.md', text);
console.log('\n\nAnalysis saved to /tmp/meme-evolution-analysis.md');
