/**
 * MCP Tool Definitions for AIMemeForge Meme Services
 *
 * Each tool maps to an x402-paywalled API endpoint.
 * Payment is handled transparently by the x402 fetch wrapper.
 * If no wallet is configured, paid tools return setup instructions.
 */

import { z } from 'zod';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const WALLET_DIR = join(homedir(), '.aimemeforge');
const WALLET_FILE = join(WALLET_DIR, 'wallet.json');

const SETUP_GUIDE = `
To use paid meme services, you need a crypto wallet with USDC.

QUICKEST WAY: Run the create_wallet tool — it generates a fresh Base wallet instantly. Then fund it with USDC.

MANUAL SETUP: If you prefer to use an existing wallet, set the PRIVATE_KEY env var:
  claude mcp add aimemeforge -e PRIVATE_KEY=0x_your_key -- npx -y @aimemeforge/mcp-server

PRICING:
  health_check     — FREE
  rate_meme        — $0.05 USDC
  generate_meme    — $0.10 USDC
  community_meme   — $0.15 USDC
  newspaper        — $0.15 USDC

Payment is automatic via x402 — no API keys, no subscriptions.
Learn more: https://aimemeforge.io
`.trim();

/**
 * Return setup instructions when wallet is not configured.
 */
function walletRequiredResponse(toolName, price) {
  return {
    content: [{
      type: 'text',
      text: `${toolName} costs $${price} USDC per call. No wallet configured.\n\nRun create_wallet to generate a fresh wallet instantly, then fund it with USDC on Base.\n\nOr run setup_wallet for manual configuration options.`,
    }],
    isError: true,
  };
}

/**
 * Register all meme service tools on the MCP server.
 * @param {McpServer} server - MCP server instance
 * @param {Function|null} fetchPaid - x402 payment-enabled fetch (null if no wallet)
 * @param {Function} fetchFree - normal fetch (for free endpoints)
 * @param {string} apiUrl - base API URL
 */
export function registerTools(server, fetchPaid, fetchFree, apiUrl) {

  // ─── Setup Guide (always available) ────────────────────────

  server.tool(
    'setup_wallet',
    'Get step-by-step instructions to set up a crypto wallet for paid meme services. Run this first if you see payment errors.',
    {},
    async () => ({
      content: [{ type: 'text', text: SETUP_GUIDE }],
    })
  );

  // ─── Create Wallet (FREE) ───────────────────────────────────

  server.tool(
    'create_wallet',
    'Create a new Base (EVM) wallet for paying meme services. Generates a fresh wallet, saves the key locally, and tells you the address to fund with USDC. Run this if you do not have a crypto wallet.',
    {},
    async () => {
      // Check if wallet already exists
      if (existsSync(WALLET_FILE)) {
        try {
          const existing = JSON.parse(readFileSync(WALLET_FILE, 'utf-8'));
          return { content: [{ type: 'text', text: [
            `Wallet already exists!`,
            ``,
            `Address: ${existing.address}`,
            `Chain: Base (EVM)`,
            `Key file: ${WALLET_FILE}`,
            ``,
            `View: https://basescan.org/address/${existing.address}`,
            `Created: ${existing.createdAt || 'unknown'}`,
            ``,
            `=== What You Can Do ===`,
            ``,
            `  check_balance  — See your USDC balance`,
            `  withdraw       — Send USDC to another address`,
            `  health_check   — Check service status`,
            ``,
            `To enable paid tools: send USDC to ${existing.address} on Base, then restart Claude Code.`,
            `Wallet is auto-loaded — no reconfiguration needed.`,
          ].join('\n') }] };
        } catch { /* corrupted file, regenerate */ }
      }

      // Generate new wallet
      const { generatePrivateKey, privateKeyToAccount } = await import('viem/accounts');
      const privateKey = generatePrivateKey();
      const account = privateKeyToAccount(privateKey);

      // Save locally
      if (!existsSync(WALLET_DIR)) mkdirSync(WALLET_DIR, { recursive: true, mode: 0o700 });
      const walletData = JSON.stringify({
        address: account.address,
        privateKey,
        chain: 'base',
        createdAt: new Date().toISOString(),
        note: 'Generated by @aimemeforge/mcp-server. Fund with USDC on Base to use paid tools.',
      }, null, 2);
      try {
        writeFileSync(WALLET_FILE, walletData, { flag: 'wx', mode: 0o600 });
      } catch (err) {
        if (err.code === 'EEXIST') {
          const existing = JSON.parse(readFileSync(WALLET_FILE, 'utf-8'));
          return { content: [{ type: 'text', text: `Wallet already exists!\nAddress: ${existing.address}\nView: https://basescan.org/address/${existing.address}` }] };
        }
        throw err;
      }

      return { content: [{ type: 'text', text: [
        `=== Wallet Created Successfully! ===`,
        ``,
        `Address: ${account.address}`,
        `Chain:   Base (EVM)`,
        `Key:     ${WALLET_FILE}`,
        `View:    https://basescan.org/address/${account.address}`,
        ``,
        `=== How to Fund ===`,
        ``,
        `Send USDC to: ${account.address}`,
        `Network: Base (Chain ID 8453)`,
        ``,
        `Ways to fund:`,
        `  - Coinbase → Send → USDC → Base network → paste address above`,
        `  - Binance → Withdraw → USDC → Base chain → paste address above`,
        `  - Any exchange that supports Base chain USDC withdrawal`,
        `  - Bridge from Ethereum: https://bridge.base.org`,
        ``,
        `Amount: $0.50 is enough for 5 memes. Gas is sponsored — you only need USDC.`,
        ``,
        `=== Activate Wallet ===`,
        ``,
        `Your wallet is saved and will be auto-loaded on next restart.`,
        `Just restart Claude Code — no need to reconfigure anything.`,
        ``,
        `=== Available Tools ===`,
        ``,
        `  check_balance           — Check USDC balance (FREE)`,
        `  health_check            — Check service status (FREE)`,
        `  generate_meme           — Generate AI meme ($0.10)`,
        `  rate_meme               — Rate a meme image ($0.05)`,
        `  generate_community_meme — Announcement meme + tweet ($0.15)`,
        `  generate_newspaper      — Newspaper banner ($0.15)`,
        `  withdraw                — Send USDC to another address`,
        ``,
        `=== Security ===`,
        ``,
        `Your private key is saved locally at: ${WALLET_FILE}`,
        `Only you have access. Back it up if you hold significant funds.`,
        `Never share your private key with anyone.`,
      ].join('\n') }] };
    }
  );

  // ─── Check Balance (FREE) ────────────────────────────────────

  server.tool(
    'check_balance',
    'Check your wallet USDC balance on Base chain. Shows address and balance so you know how many memes you can generate.',
    {},
    async () => {
      // Try env var first, then saved wallet
      let address = null;
      let source = '';
      if (fetchPaid) {
        // Wallet is configured via env — derive address
        try {
          const pk = process.env.PRIVATE_KEY;
          if (pk) {
            const { privateKeyToAccount } = await import('viem/accounts');
            const account = privateKeyToAccount(pk);
            address = account.address;
            source = 'configured wallet';
          }
        } catch {}
      }
      if (!address && existsSync(WALLET_FILE)) {
        try {
          const w = JSON.parse(readFileSync(WALLET_FILE, 'utf-8'));
          address = w.address;
          source = 'saved wallet';
        } catch {}
      }
      if (!address) {
        return { content: [{ type: 'text', text: 'No wallet found. Run create_wallet first.' }], isError: true };
      }

      // Check USDC balance on Base via public RPC
      try {
        const USDC_BASE = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
        const balanceCall = {
          jsonrpc: '2.0', id: 1, method: 'eth_call',
          params: [{
            to: USDC_BASE,
            data: '0x70a08231000000000000000000000000' + address.slice(2).toLowerCase(),
          }, 'latest'],
        };
        const res = await fetchFree('https://mainnet.base.org', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(balanceCall),
        });
        const data = await res.json();
        const rawBalance = parseInt(data.result || '0', 16);
        const usdc = (rawBalance / 1e6).toFixed(2);

        const memeCount = Math.floor(rawBalance / 100000); // $0.10 per meme
        return { content: [{ type: 'text', text: [
          `Wallet: ${address} (${source})`,
          `Balance: ${usdc} USDC (Base)`,
          ``,
          `Can generate ~${memeCount} memes at $0.10 each`,
          ``,
          `Fund this address with USDC on Base chain to add more credits.`,
          `View on Basescan: https://basescan.org/address/${address}`,
        ].join('\n') }] };
      } catch (err) {
        return { content: [{ type: 'text', text: `Wallet: ${address}\nBalance check failed: ${err.message}` }], isError: true };
      }
    }
  );

  // ─── Withdraw USDC ──────────────────────────────────────────

  server.tool(
    'withdraw',
    'Send USDC from your wallet to another address on Base chain. Use this to withdraw funds or pay someone.',
    {
      to: z.string().describe('Recipient address (0x...)'),
      amount: z.string().describe('Amount in USDC (e.g. "1.50")'),
    },
    async ({ to, amount }) => {
      // Get private key
      let privateKey = process.env.PRIVATE_KEY;
      if (!privateKey && existsSync(WALLET_FILE)) {
        try {
          const w = JSON.parse(readFileSync(WALLET_FILE, 'utf-8'));
          privateKey = w.privateKey;
        } catch {}
      }
      if (!privateKey) {
        return { content: [{ type: 'text', text: 'No wallet configured. Run create_wallet first.' }], isError: true };
      }

      // Validate
      if (!to.match(/^0x[0-9a-fA-F]{40}$/)) {
        return { content: [{ type: 'text', text: 'Invalid address. Must be 0x... (42 chars).' }], isError: true };
      }
      const usdcAmount = parseFloat(amount);
      if (isNaN(usdcAmount) || usdcAmount <= 0) {
        return { content: [{ type: 'text', text: 'Invalid amount. Must be a positive number.' }], isError: true };
      }
      const MAX_WITHDRAWAL = parseFloat(process.env.AIMEMEFORGE_MAX_WITHDRAWAL || '10');
      if (usdcAmount > MAX_WITHDRAWAL) {
        return { content: [{ type: 'text', text: `Withdrawal capped at $${MAX_WITHDRAWAL} USDC per transaction for safety.\nSet AIMEMEFORGE_MAX_WITHDRAWAL env var to adjust.` }], isError: true };
      }

      try {
        const { createWalletClient, http, parseUnits, encodeFunctionData } = await import('viem');
        const { privateKeyToAccount } = await import('viem/accounts');
        const { base } = await import('viem/chains');

        const account = privateKeyToAccount(privateKey);
        const client = createWalletClient({
          account,
          chain: base,
          transport: http('https://mainnet.base.org'),
        });

        const USDC_BASE = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
        const rawAmount = parseUnits(amount, 6); // USDC has 6 decimals

        // ERC-20 transfer(address,uint256)
        const data = encodeFunctionData({
          abi: [{ name: 'transfer', type: 'function', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ name: '', type: 'bool' }] }],
          functionName: 'transfer',
          args: [to, rawAmount],
        });

        const hash = await client.sendTransaction({
          to: USDC_BASE,
          data,
        });

        return { content: [{ type: 'text', text: [
          `Transfer sent!`,
          ``,
          `From: ${account.address}`,
          `To: ${to}`,
          `Amount: ${amount} USDC`,
          `Tx: https://basescan.org/tx/${hash}`,
          ``,
          `Transaction may take ~2 seconds to confirm on Base.`,
        ].join('\n') }] };
      } catch (err) {
        const msg = err.message || String(err);
        if (msg.includes('insufficient')) {
          return { content: [{ type: 'text', text: `Transfer failed: Insufficient balance. Check with check_balance tool.\nAlso ensure you have a tiny amount of ETH on Base for gas (~$0.001).` }], isError: true };
        }
        return { content: [{ type: 'text', text: `Transfer failed: ${msg.slice(0, 300)}` }], isError: true };
      }
    }
  );

  // ─── Health Check (FREE) ───────────────────────────────────

  server.tool(
    'health_check',
    'Check if AIMemeForge is online. Free, no wallet required.',
    {},
    async () => {
      try {
        const res = await fetchFree(`${apiUrl}/health`);
        const data = await res.json();
        return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { content: [{ type: 'text', text: `Health check failed: ${err.message}` }], isError: true };
      }
    }
  );

  // ─── Rate Meme ($0.05 USDC) ────────────────────────────────

  server.tool(
    'rate_meme',
    'Rate a meme image with AI vision analysis. Returns score (0-100), grade, and suggestions. Costs $0.05 USDC.',
    {
      imageUrl: z.string().url().describe('Public URL of the meme image to rate'),
    },
    async ({ imageUrl }) => {
      if (!fetchPaid) return walletRequiredResponse('rate_meme', '0.05');
      const res = await fetchPaid(`${apiUrl}/api/memes/rate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ imageUrl }),
      });
      if (!res.ok) {
        return { content: [{ type: 'text', text: `Error (${res.status}): ${await res.text()}` }], isError: true };
      }
      const data = await res.json();
      const summary = [
        `Score: ${data.score}/100 (${data.grade})`,
        `Pass: ${data.pass ? 'Yes' : 'No'}`,
        data.suggestions?.length ? `Suggestions:\n${data.suggestions.map(s => `  - ${s}`).join('\n')}` : '',
      ].filter(Boolean).join('\n');
      return { content: [{ type: 'text', text: summary }] };
    }
  );

  // ─── Generate Meme ($0.10 USDC) ────────────────────────────

  server.tool(
    'generate_meme',
    'Generate an AI crypto meme from a topic or news headline. Returns image URL, title, and quality score. Costs $0.10 USDC.',
    {
      topic: z.string().describe('Meme topic or news headline (required)'),
      artStyleId: z.string().optional().describe('Art style: pixel-art, cyberpunk, watercolor, comic-book, vaporwave, ukiyo-e, bauhaus, synthwave, claymation, stained-glass'),
    },
    async ({ topic, artStyleId }) => {
      if (!fetchPaid) return walletRequiredResponse('generate_meme', '0.10');
      const body = { topic };
      if (artStyleId) body.artStyleId = artStyleId;
      const res = await fetchPaid(`${apiUrl}/api/memes/generate-custom`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        return { content: [{ type: 'text', text: `Error (${res.status}): ${await res.text()}` }], isError: true };
      }
      const data = await res.json();
      const meme = data.meme || data;
      const summary = [
        `Title: ${meme.title}`,
        `Image: ${meme.imageUrl}`,
        `Tags: ${(meme.tags || []).join(', ')}`,
        `Quality: ${meme.metadata?.qualityScore || 'N/A'}/100`,
        `Style: ${meme.metadata?.artStyleName || 'auto'}`,
      ].join('\n');
      return { content: [
        { type: 'text', text: summary },
        { type: 'resource', resource: { uri: meme.imageUrl, mimeType: 'image/png', text: meme.title } },
      ] };
    }
  );

  // ─── Generate Community Meme ($0.15 USDC) ──────────────────

  server.tool(
    'generate_community_meme',
    'Turn a project announcement into a shareable meme with suggested tweet. Choose tone and visual style. Costs $0.15 USDC.',
    {
      description: z.string().max(500).describe('Project announcement or event (max 500 chars)'),
      tone: z.enum(['hype', 'wholesome', 'funny', 'flex']).optional().describe('Meme tone (default: hype)'),
      style: z.enum(['meme', 'announcement', 'comic', 'infographic']).optional().describe('Visual style (default: meme)'),
    },
    async ({ description, tone, style }) => {
      if (!fetchPaid) return walletRequiredResponse('generate_community_meme', '0.15');
      const res = await fetchPaid(`${apiUrl}/api/memes/generate-community`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ description, tone: tone || 'hype', style: style || 'meme' }),
      });
      if (!res.ok) {
        return { content: [{ type: 'text', text: `Error (${res.status}): ${await res.text()}` }], isError: true };
      }
      const data = await res.json();
      const meme = data.meme || data;
      const summary = [
        `Title: ${meme.title}`,
        `Image: ${meme.imageUrl}`,
        data.suggestedTweet ? `\nSuggested Tweet:\n${data.suggestedTweet}` : '',
      ].filter(Boolean).join('\n');
      return { content: [{ type: 'text', text: summary }] };
    }
  );

  // ─── Generate Newspaper ($0.15 USDC) ───────────────────────

  server.tool(
    'generate_newspaper',
    'Generate a newspaper-style banner image from news text. Great for X posts. Costs $0.15 USDC.',
    {
      description: z.string().max(500).describe('News or announcement text (max 500 chars)'),
      xProfileUrl: z.string().url().optional().describe('X/Twitter profile URL for avatar in the newspaper'),
    },
    async ({ description, xProfileUrl }) => {
      if (!fetchPaid) return walletRequiredResponse('generate_newspaper', '0.15');
      const body = { description };
      if (xProfileUrl) body.xProfileUrl = xProfileUrl;
      const res = await fetchPaid(`${apiUrl}/api/memes/generate-newspaper`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        return { content: [{ type: 'text', text: `Error (${res.status}): ${await res.text()}` }], isError: true };
      }
      const data = await res.json();
      const meme = data.meme || data;
      const summary = [
        `Title: ${meme.title}`,
        `Image: ${meme.imageUrl}`,
        data.suggestedTweet ? `\nSuggested Tweet:\n${data.suggestedTweet}` : '',
      ].filter(Boolean).join('\n');
      return { content: [{ type: 'text', text: summary }] };
    }
  );
}
